config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about' => "homes#about", as: 'about'
  devise_for :users
  resources :users, only: [:show, :edit, :update, :index]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.book_id = @book.id
    if @book_comment.save
      redirect_to book_path(@book.id)
    else
      @user = @book.user
      @book0 = Book.new
      render 'books/show'
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = @book.user
    @book0 = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    redirect_to request. referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book0 = Book.new
  end

  def index
    @users = User.all
    @user = User.new
    @book = Book.new
    @user0 = User.find(current_user.id)
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
     @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      
      <% if @book.errors.any? %>
      <%= @book.errors.count %> errors prohibited this obj from being saved: %>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
      
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <p>Title</p>
          <%= f.text_field :title, class: "form-control book_title" %>      
        </div>
        <div class="form-group">
          <p>Opinion</p>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>  
        </div>
      <% end %>
      
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @user, book: @book %>

    <div class="col-md-8 offset-md-1" >
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan = "3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
            </td>
            <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
            </td>
            <td><%= book.body %></td>
            <td>
            <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fas fa-heart text-danger"></i>
                  <%= book.favorites.count %>
                <% end %>
            <% else %>
                <%= link_to  book_favorites_path(book), method: :post do %>
                  <i class="fas fa-heart"></i>
                  <%= book.favorites.count %>
                <% end %>
            <% end %>
            </td>
            <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'users/sidebar', user: @user, book: @book0 %>

    <div class="col-md-8 offset-md-1 ">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@user.id) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %></br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book.id) do %>
              <%= @book.title %>
            <% end %>
          </td>
          <td>
            <%= @book.body %>
          </td>
          <% if @book.user == current_user %>
          <td>
            <%= link_to(edit_book_path(@book), class: "btn btn-sm btn-success") do %>
              Edit
            <% end %>
          </td>
          <td>
            <%= link_to(book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger") do %>
              Destroy
            <% end %>
          </td>
          <% end %>
          <td>
            <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  <i class="fas fa-heart text-danger"></i>
                  <%= @book.favorites.count %>
                <% end %>
            <% else %>
                <%= link_to  book_favorites_path(@book), method: :post do %>
                  <i class="fas fa-heart"></i>
                  <%= @book.favorites.count %>
                <% end %>
            <% end %>
          </td>
          <td>コメント数：<%= @book.book_comments.count %></td>
        </tr>
      </table>
      <table>
       <% @book.book_comments.each do |book_comment| %>
       <tr>
         <td>
           <%= image_tag book_comment.user.get_profile_image(50,50) %>
           <br><%= book_comment.user.name %>
         </td>
         <td>
          <%= book_comment.comment %>
         </td>
         <td>
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn btn-sm btn-danger" %>
            <% end %>
         </td>
       </tr>
       <% end %>
      </table>
      <div class="form-group">
        <%= form_with model: [@book, @book_comment] do |f| %>
          <%= f.text_area :comment, rows: '5', class: "form-control book_comment" %>
          <%= f.submit "送信", class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
    <div class="row">
        <h1 class="px-3 mx-auto" >
            Welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
            </h1>
    </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
      </h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
    
      <div class="btn-wrapper col-10 mx-auto">
      <% if user_signed_in? %>
        <div class="row">
          <%= link_to(user_path(current_user.id), class: "btn btn-info btn-sm btn-block mb-3 sign_in") do %>Log in<% end %>
        </div>
        <div class="row">
          <%= link_to(user_path(current_user.id), class: "btn btn-success btn-sm btn-block sign_up") do %>Sign up<% end %>
        </div>
      <% else %>
        <div class="row">
          <%= link_to(new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in") do %>Log in<% end %>
        </div>
        <div class="row">
          <%= link_to(new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up") do %>Sign up<% end %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
      	  <div class="navbar-collapse collapse">
      	    <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to(user_path(current_user), class: "nav-link text-light") do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to(users_path, class: "nav-link text-light") do %>
                  <i class="fas fa-users"></i>
                  Users
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to(books_path, class: "nav-link text-light") do %>
                  <i class="fas fa-book-open"></i>
                  Books
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to(destroy_user_session_path, method: :delete, class: "nav-link text-light") do  %>
                  <i class="fas fa-sign-out-alt"></i>
                  logout
                <% end %>
              </li>

            <% else %>
            <li class="nav-item">
                <%= link_to(root_path, class: "nav-link text-light") do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to(about_path, class: "nav-link text-light") do %>
                  <i class="fas fa-link"></i>
                  About
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to(new_user_registration_path, class: "nav-link text-light") do %>
                  <i class="fas fa-user-plus"></i>
                   sign up
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to(user_session_path, class: "nav-link text-light") do  %>
                  <i class="fas fa-sign-in-alt"></i>
                  login
                <% end %>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <p id= "notice">
        <% if flash[:notice] %>
        <%= flash[:notice] %>
        <% end %>
      </p>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_sidebar.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to(edit_user_path(user.id), class: "btn btn-outline-secondary btn-block") do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: book do |f| %>
  <div class="form-group">
    <h6>Title</h6>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <h6>Opinion</h6>
    <%= f.text_area :body, class: "form-control book_body" %>    
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
  
  <% if @user.errors.any? %>
  <%= @user.errors.count %> errors prohibited this obj from being saved: %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  
  <%= form_with model: @user do |f| %>
    <div class="form-group">
      <label for="inputName">Name</label>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control name"%>  
    </div>
    <div class="form-group">
      <label for="inputImage">Image</label>
      <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*", class: "form-control-file user-image" %>  
    </div>
    <div class="form-group">
      <p>Introduction</p>
      <%= f.text_area :introduction , class: "form-control introduction" %>      
    </div>
    <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @user0, book: @book %>
  
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan = "3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(100,100) %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @user, book: @book0 %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan = "3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
            <%= link_to user_path(@user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
            </td>
            <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
            </td>
            <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fas fa-heart text-danger"></i>
                    <%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to  book_favorites_path(book), method: :post do %>
                    <i class="fas fa-heart"></i>
                    <%= book.favorites.count %>
                  <% end %>
                <% end %>
              </td>
            <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>